#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sun Nov 22 10:32:20 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.textpanel = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, "7")
        self.button_2 = wx.Button(self, wx.ID_ANY, "8")
        self.button_3 = wx.Button(self, wx.ID_ANY, "9")
        self.button_4 = wx.Button(self, wx.ID_ANY, "/")
        self.button_5 = wx.Button(self, wx.ID_ANY, "4")
        self.button_6 = wx.Button(self, wx.ID_ANY, "5")
        self.button_7 = wx.Button(self, wx.ID_ANY, "6")
        self.button_8 = wx.Button(self, wx.ID_ANY, "*")
        self.button_9 = wx.Button(self, wx.ID_ANY, "1")
        self.button_10 = wx.Button(self, wx.ID_ANY, "2")
        self.button_11 = wx.Button(self, wx.ID_ANY, "3")
        self.button_12 = wx.Button(self, wx.ID_ANY, "-")
        self.button_13 = wx.Button(self, wx.ID_ANY, ".")
        self.button_14 = wx.Button(self, wx.ID_ANY, "0")
        self.button_15 = wx.Button(self, wx.ID_ANY, "C")
        self.button_16 = wx.Button(self, wx.ID_ANY, "+")
        self.clearbtn = wx.Button(self, wx.ID_ANY, "Clear")
        self.equal = wx.Button(self, wx.ID_ANY, "=")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        mainsizer = wx.BoxSizer(wx.VERTICAL)
        Sizer = wx.BoxSizer(wx.HORIZONTAL)
        btnsizer = wx.GridSizer(4, 4, 5, 5)
        mainsizer.Add(self.textpanel, 0, wx.ALL | wx.EXPAND, 5)
        btnsizer.Add(self.button_1, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_2, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_3, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_4, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_5, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_6, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_7, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_8, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_9, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_10, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_11, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_12, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_13, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_14, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_15, 1, wx.EXPAND, 0)
        btnsizer.Add(self.button_16, 1, wx.EXPAND, 0)
        mainsizer.Add(btnsizer, 2, wx.EXPAND, 0)
        Sizer.Add(self.clearbtn, 1, wx.ALL | wx.EXPAND, 5)
        Sizer.Add(self.equal, 1, wx.ALL | wx.EXPAND, 5)
        mainsizer.Add(Sizer, 1, wx.EXPAND, 0)
        self.SetSizer(mainsizer)
        mainsizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
